//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mantencion
    {
        public int IdMantencion { get; set; }
        public string TituloMantencion { get; set; }
        public Nullable<System.DateTime> FechaEmisionMantencion { get; set; }
        public Nullable<System.DateTime> FechaRealizacionMantencion { get; set; }
        public Nullable<System.TimeSpan> HoraMantencion { get; set; }
        public string Responsable { get; set; }
        public string TipoMantencion { get; set; }
        public string ObservacionMantencion { get; set; }
        public string DescripcionMantencion { get; set; }
    
        public virtual Maquinaria Maquinaria { get; set; }
        public virtual Recurso Recurso { get; set; }
        public virtual Responsable Responsable1 { get; set; }
        public virtual Solicitud Solicitud { get; set; }
    }
}
