//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maquinaria
    {
        public int IdMaquinaria { get; set; }
        public string NombreMaquinaria { get; set; }
        public string TipoMaquinaria { get; set; }
        public Nullable<int> NumeroMaquinaria { get; set; }
        public Nullable<int> AñoMaquinaria { get; set; }
        public string MarcaMaquinaria { get; set; }
        public string ModeloMaquinaria { get; set; }
        public Nullable<int> NumeroMotorMaquinaria { get; set; }
        public string RendimientoMaquinaria { get; set; }
        public Nullable<int> CapacidadAceiteMaquinaria { get; set; }
        public Nullable<int> CapacidadCombustible { get; set; }
    
        public virtual Mantencion Mantencion { get; set; }
        public virtual Repuesto Repuesto { get; set; }
    }
}
