//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repuesto
    {
        public int IdRepuesto { get; set; }
        public string NombreRepuesto { get; set; }
        public Nullable<int> StockRepuesto { get; set; }
        public string TipoRepuesto { get; set; }
    
        public virtual Maquinaria Maquinaria { get; set; }
    }
}
