//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Responsable
    {
        public int IdResponsable { get; set; }
        public string NombreResponsable { get; set; }
        public string ApellidoResponsable { get; set; }
        public string RutResponsable { get; set; }
        public string RolResponsable { get; set; }
        public Nullable<int> CelularResponsable { get; set; }
        public string CorreoResponsable { get; set; }
    
        public virtual Mantencion Mantencion { get; set; }
    }
}
